workflows:
  android-workflow:
    name: Android Build
    environment:
      flutter: 3.47.1
      java: 17
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/**/*.apk
